- name: Test conditionals
  hosts: web
  gather_facts: false
  tasks:
  - name: touch files with an optional mode
    file: dest={{ item.path }} state=touch mode={{ item.mode | default(omit) }}
    loop:
      - path: /tmp/foo
      - path: /tmp/bar
      - path: /tmp/baz
        mode: "0444"
